application: wt-facebook
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts 
  static_dir: scripts

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  
- url: /.*
  script: wt-facebook.py
  
